apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexo-examples-py
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 40
      timeoutSeconds: 30
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/nexo-examples/nexo-examples-py:latest
          ports:
            - containerPort: 8080
          env:
            - name: EVENT_TTL_SECONDS
              value: "86400"
            - name: MAX_EVENTS_PER_KEY
              value: "200"
